name: GH build for ezcv

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version number'
        required: true
        type: int
      description:
        description: 'Describe your changes'
        required: true
        type: str
    
jobs:
  printInput:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo Inputs are ${{ inputs.version_number }} ${{ inputs.description }}
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install ezcv

    - name: build html files
      run: |
        python -m ezcv build

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site
